apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-knative
  namespace: demo-apps
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          env:
            - name: TARGET
              value: "Knative"
